// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkrwAvFRcLSPSB4ChN-te0mQteE9Lcgj4',
    appId: '1:610128359003:web:62bb9353ef88f539e6d97e',
    messagingSenderId: '610128359003',
    projectId: 'car-wash-b0813',
    authDomain: 'car-wash-b0813.firebaseapp.com',
    storageBucket: 'car-wash-b0813.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk44HU5HSM6mga8fHUTyIpKyswpOJN8VU',
    appId: '1:610128359003:android:8fecfa797242f09ce6d97e',
    messagingSenderId: '610128359003',
    projectId: 'car-wash-b0813',
    storageBucket: 'car-wash-b0813.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtZlYY29-_hhs9BT_HMgNEUMjWIdITqqs',
    appId: '1:610128359003:ios:7ff4550e37b34812e6d97e',
    messagingSenderId: '610128359003',
    projectId: 'car-wash-b0813',
    storageBucket: 'car-wash-b0813.appspot.com',
    iosBundleId: 'com.example.carWash',
  );
}
